@startuml
  "default" -> "fs/open.o"++: do_sys_open
    "fs/open.o" -> "fs/open.o"++: do_sys_openat2
      "fs/open.o" -> "fs/namei.o"++: getname
        "fs/namei.o" -> "fs/namei.o"++: getname_flags
          "fs/namei.o" -> "mm/slub.o"++: kmem_cache_alloc_noprof
            "mm/slub.o" -> "mm/slub.o": prefetch_freepointer.isra.0
          "mm/slub.o" --> "fs/namei.o"--: ret
        "fs/namei.o" --> "fs/namei.o"--: ret
      "fs/namei.o" --> "fs/open.o"--: ret
      "fs/open.o" -> "fs/file.o"++: get_unused_fd_flags
        "fs/file.o" -> "fs/file.o"++: __get_unused_fd_flags
          "fs/file.o" -> "fs/file.o"++: alloc_fd
            "fs/file.o" -> "default": _raw_spin_lock
            "fs/file.o" -> "fs/file.o": find_next_fd
            "fs/file.o" -> "default": _raw_spin_unlock
          "fs/file.o" --> "fs/file.o"--: ret
        "fs/file.o" --> "fs/file.o"--: ret
      "fs/file.o" --> "fs/open.o"--: ret
      "fs/open.o" -> "fs/namei.o"++: do_filp_open
        "fs/namei.o" -> "fs/namei.o": __set_nameidata
        "fs/namei.o" -> "fs/namei.o"++: path_openat
          "fs/namei.o" -> "fs/file_table.o"++: alloc_empty_file
            "fs/file_table.o" -> "fs/file_table.o": get_nr_files
            "fs/file_table.o" -> "mm/slub.o"++: kmem_cache_alloc_noprof
              "mm/slub.o" -> "mm/slub.o": prefetch_freepointer.isra.0
            "mm/slub.o" --> "fs/file_table.o"--: ret
            "fs/file_table.o" -> "fs/file_table.o"++: init_file
              "fs/file_table.o" -> "default": security_file_alloc
              "fs/file_table.o" -> "default": __mutex_init
            "fs/file_table.o" --> "fs/file_table.o"--: ret
          "fs/file_table.o" --> "fs/namei.o"--: ret
          "fs/namei.o" -> "fs/namei.o"++: path_init
            "fs/namei.o" -> "default": __rcu_read_lock
            "fs/namei.o" -> "fs/namei.o"++: nd_jump_root
              "fs/namei.o" -> "fs/namei.o": set_root
            "fs/namei.o" --> "fs/namei.o"--: ret
          "fs/namei.o" --> "fs/namei.o"--: ret
          "fs/namei.o" -> "fs/namei.o"++: link_path_walk
            "fs/namei.o" -> "fs/namei.o"++: inode_permission
              "fs/namei.o" -> "fs/namei.o": sb_permission
              "fs/namei.o" -> "fs/namei.o"++: generic_permission
                "fs/namei.o" -> "fs/namei.o"++: acl_permission_check
                  "fs/namei.o" -> "fs/mnt_idmapping.o": make_vfsuid
                "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "default": security_inode_permission
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: walk_component
              "fs/namei.o" -> "fs/namei.o"++: lookup_fast
                "fs/namei.o" -> "fs/dcache.o": __d_lookup_rcu
              "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "fs/namei.o"++: step_into
                "fs/namei.o" -> "fs/namei.o"++: __follow_mount_rcu
                  "fs/namei.o" -> "fs/namespace.o": __lookup_mnt
                "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: inode_permission
              "fs/namei.o" -> "fs/namei.o": sb_permission
              "fs/namei.o" -> "fs/kernfs/inode.o": kernfs_iop_permission
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: try_to_unlazy
              "fs/namei.o" -> "fs/namei.o": legitimize_links
              "fs/namei.o" -> "fs/namei.o"++: __legitimize_path
                "fs/namei.o" -> "fs/namespace.o": __legitimize_mnt
              "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "fs/namei.o"++: legitimize_root
                "fs/namei.o" -> "fs/namei.o"++: __legitimize_path
                  "fs/namei.o" -> "fs/namespace.o": __legitimize_mnt
                "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "fs/namei.o"++: leave_rcu
                "fs/namei.o" -> "default": __rcu_read_unlock
              "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: inode_permission
              "fs/namei.o" -> "fs/namei.o": sb_permission
              "fs/namei.o" -> "fs/kernfs/inode.o"++: kernfs_iop_permission
                "fs/kernfs/inode.o" -> "default": down_read
                "fs/kernfs/inode.o" -> "fs/kernfs/inode.o"++: kernfs_refresh_inode
                  "fs/kernfs/inode.o" -> "fs/inode.o": set_nlink
                "fs/kernfs/inode.o" --> "fs/kernfs/inode.o"--: ret
                "fs/kernfs/inode.o" -> "fs/namei.o"++: generic_permission
                  "fs/namei.o" -> "fs/namei.o": acl_permission_check
                "fs/namei.o" --> "fs/kernfs/inode.o"--: ret
                "fs/kernfs/inode.o" -> "default": up_read
              "fs/kernfs/inode.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "default": security_inode_permission
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: walk_component
              "fs/namei.o" -> "fs/namei.o"++: lookup_fast
                "fs/namei.o" -> "fs/dcache.o"++: __d_lookup
                  "fs/dcache.o" -> "default": __rcu_read_lock
                  "fs/dcache.o" -> "default": _raw_spin_lock
                  "fs/dcache.o" -> "fs/dcache.o": d_same_name
                  "fs/dcache.o" -> "default": _raw_spin_unlock
                  "fs/dcache.o" -> "default": __rcu_read_unlock
                "fs/dcache.o" --> "fs/namei.o"--: ret
                "fs/namei.o" -> "fs/kernfs/dir.o"++: kernfs_dop_revalidate
                  "fs/kernfs/dir.o" -> "default": down_read
                  "fs/kernfs/dir.o" -> "default": up_read
                "fs/kernfs/dir.o" --> "fs/namei.o"--: ret
              "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "fs/namei.o"++: step_into
                "fs/namei.o" -> "fs/dcache.o"++: dput
                  "fs/dcache.o" -> "default": __rcu_read_lock
                  "fs/dcache.o" -> "default": __rcu_read_unlock
                "fs/dcache.o" --> "fs/namei.o"--: ret
              "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: inode_permission
              "fs/namei.o" -> "fs/namei.o": sb_permission
              "fs/namei.o" -> "fs/kernfs/inode.o"++: kernfs_iop_permission
                "fs/kernfs/inode.o" -> "default": down_read
                "fs/kernfs/inode.o" -> "fs/kernfs/inode.o"++: kernfs_refresh_inode
                  "fs/kernfs/inode.o" -> "fs/inode.o": set_nlink
                "fs/kernfs/inode.o" --> "fs/kernfs/inode.o"--: ret
                "fs/kernfs/inode.o" -> "fs/namei.o"++: generic_permission
                  "fs/namei.o" -> "fs/namei.o": acl_permission_check
                "fs/namei.o" --> "fs/kernfs/inode.o"--: ret
                "fs/kernfs/inode.o" -> "default": up_read
              "fs/kernfs/inode.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "default": security_inode_permission
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: walk_component
              "fs/namei.o" -> "fs/namei.o"++: lookup_fast
                "fs/namei.o" -> "fs/dcache.o"++: __d_lookup
                  "fs/dcache.o" -> "default": __rcu_read_lock
                  "fs/dcache.o" -> "default": _raw_spin_lock
                  "fs/dcache.o" -> "fs/dcache.o": d_same_name
                  "fs/dcache.o" -> "default": _raw_spin_unlock
                  "fs/dcache.o" -> "default": __rcu_read_unlock
                "fs/dcache.o" --> "fs/namei.o"--: ret
                "fs/namei.o" -> "fs/kernfs/dir.o"++: kernfs_dop_revalidate
                  "fs/kernfs/dir.o" -> "default": down_read
                  "fs/kernfs/dir.o" -> "default": up_read
                "fs/kernfs/dir.o" --> "fs/namei.o"--: ret
              "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "fs/namei.o"++: step_into
                "fs/namei.o" -> "fs/namei.o"++: __traverse_mounts
                  "fs/namei.o" -> "fs/namespace.o"++: lookup_mnt
                    "fs/namespace.o" -> "default": __rcu_read_lock
                    "fs/namespace.o" -> "fs/namespace.o": __lookup_mnt
                    "fs/namespace.o" -> "fs/namespace.o": __legitimize_mnt
                    "fs/namespace.o" -> "default": __rcu_read_unlock
                  "fs/namespace.o" --> "fs/namei.o"--: ret
                  "fs/namei.o" -> "default"++: irq_enter_rcu
                    "default" -> "default": irqtime_account_irq
                  "default" --> "fs/namei.o"--: ret
                  "fs/namei.o" -> "default"++: do_interrupt_handler
                    "default" -> "default"++: gic_handle_irq
                      "default" -> "default"++: generic_handle_domain_irq
                        "default" -> "default"++: __irq_resolve_mapping
                          "default" -> "default": __rcu_read_lock
                          "default" -> "default": __rcu_read_unlock
                        "default" --> "default"--: ret
                        "default" -> "default"++: handle_irq_desc
                          "default" -> "default"++: handle_percpu_devid_irq
                            "default" -> "default"++: arch_timer_handler_virt
                              "default" -> "default"++: hrtimer_interrupt
                                "default" -> "default": _raw_spin_lock_irqsave
                                "default" -> "default"++: ktime_get_update_offsets_now
                                  "default" -> "default": arch_counter_read
                                "default" --> "default"--: ret
                                "default" -> "default"++: __hrtimer_run_queues
                                  "default" -> "default": __remove_hrtimer
                                  "default" -> "default": _raw_spin_unlock_irqrestore
                                  "default" -> "default"++: tick_nohz_handler
                                    "default" -> "default"++: ktime_get
                                      "default" -> "default": arch_counter_read
                                    "default" --> "default"--: ret
                                    "default" -> "default"++: tick_do_update_jiffies64
                                      "default" -> "default": _raw_spin_lock
                                      "default" -> "default": calc_global_load
                                      "default" -> "default": _raw_spin_unlock
                                      "default" -> "default"++: update_wall_time
                                        "default" -> "default"++: timekeeping_advance
                                          "default" -> "default": _raw_spin_lock_irqsave
                                          "default" -> "default": arch_counter_read
                                          "default" -> "default": ntp_tick_length
                                          "default" -> "default": ntp_tick_length
                                          "default" -> "default"++: timekeeping_update_from_shadow.constprop.0
                                            "default" -> "default": ntp_get_next_leap
                                            "default" -> "default": update_vsyscall
                                            "default" -> "default"++: raw_notifier_call_chain
                                              "default" -> "default": notifier_call_chain
                                            "default" --> "default"--: ret
                                            "default" -> "default": update_fast_timekeeper
                                            "default" -> "default": update_fast_timekeeper
                                          "default" --> "default"--: ret
                                          "default" -> "default": _raw_spin_unlock_irqrestore
                                        "default" --> "default"--: ret
                                      "default" --> "default"--: ret
                                    "default" --> "default"--: ret
                                    "default" -> "default"++: update_process_times
                                      "default" -> "default"++: account_process_tick
                                        "default" -> "default"++: irqtime_account_process_tick
                                          "default" -> "default"++: account_system_index_time
                                            "default" -> "default": cpuacct_account_field
                                            "default" -> "default"++: acct_account_cputime
                                              "default" -> "default": __acct_update_integrals
                                            "default" --> "default"--: ret
                                          "default" --> "default"--: ret
                                        "default" --> "default"--: ret
                                      "default" --> "default"--: ret
                                      "default" -> "default": hrtimer_run_queues
                                      "default" -> "default": tmigr_requires_handle_remote
                                      "default" -> "default"++: rcu_sched_clock_irq
                                        "default" -> "default": rcu_qs
                                        "default" -> "default": rcu_is_cpu_rrupt_from_idle
                                        "default" -> "default": rcu_segcblist_ready_cbs
                                        "default" -> "default": rcu_is_cpu_rrupt_from_idle
                                      "default" --> "default"--: ret
                                      "default" -> "default"++: sched_tick
                                        "default" -> "default": topology_scale_freq_tick
                                        "default" -> "default"++: raw_spin_rq_lock_nested
                                          "default" -> "default": _raw_spin_lock
                                        "default" --> "default"--: ret
                                        "default" -> "default": update_rq_clock
                                        "default" -> "default"++: update_hw_load_avg
                                          "default" -> "default": decay_load
                                          "default" -> "default": decay_load
                                          "default" -> "default": decay_load
                                        "default" --> "default"--: ret
                                        "default" -> "default"++: task_tick_fair
                                          "default" -> "default"++: update_curr
                                            "default" -> "default"++: update_min_vruntime
                                              "default" -> "default": __pick_root_entity
                                            "default" --> "default"--: ret
                                            "default" -> "default": cpuacct_charge
                                            "default" -> "default"++: dl_server_update
                                              "default" -> "default"++: update_curr_dl_se
                                                "default" -> "default": dl_scaled_delta_exec
                                              "default" --> "default"--: ret
                                            "default" --> "default"--: ret
                                          "default" --> "default"--: ret
                                          "default" -> "default"++: __update_load_avg_se
                                            "default" -> "default": decay_load
                                            "default" -> "default": decay_load
                                            "default" -> "default": decay_load
                                            "default" -> "default"++: __accumulate_pelt_segments
                                              "default" -> "default": decay_load
                                              "default" -> "default": decay_load
                                            "default" --> "default"--: ret
                                          "default" --> "default"--: ret
                                          "default" -> "default"++: __update_load_avg_cfs_rq
                                            "default" -> "default": decay_load
                                            "default" -> "default": decay_load
                                            "default" -> "default": decay_load
                                            "default" -> "default"++: __accumulate_pelt_segments
                                              "default" -> "default": decay_load
                                              "default" -> "default": decay_load
                                            "default" --> "default"--: ret
                                          "default" --> "default"--: ret
                                          "default" -> "default": update_cfs_group
                                          "default" -> "default"++: update_curr
                                            "default" -> "default"++: update_min_vruntime
                                              "default" -> "default": __pick_root_entity
                                            "default" --> "default"--: ret
                                            "default" -> "default"++: resched_curr_lazy
                                              "default" -> "default": resched_curr
                                            "default" --> "default"--: ret
                                            "default" -> "default": clear_buddies.isra.0
                                          "default" --> "default"--: ret
                                          "default" -> "default"++: __update_load_avg_se
                                            "default" -> "default": decay_load
                                            "default" -> "default": decay_load
                                            "default" -> "default": decay_load
                                            "default" -> "default"++: __accumulate_pelt_segments
                                              "default" -> "default": decay_load
                                              "default" -> "default": decay_load
                                            "default" --> "default"--: ret
                                          "default" --> "default"--: ret
                                          "default" -> "default"++: __update_load_avg_cfs_rq
                                            "default" -> "default": decay_load
                                            "default" -> "default": decay_load
                                            "default" -> "default": decay_load
                                            "default" -> "default"++: __accumulate_pelt_segments
                                              "default" -> "default": decay_load
                                              "default" -> "default": decay_load
                                            "default" --> "default"--: ret
                                          "default" --> "default"--: ret
                                          "default" -> "default": update_cfs_group
                                        "default" --> "default"--: ret
                                        "default" -> "default": calc_global_load_tick
                                        "default" -> "default"++: task_tick_mm_cid
                                          "default" -> "default"++: task_work_add
                                            "default" -> "default": kick_process
                                          "default" --> "default"--: ret
                                        "default" --> "default"--: ret
                                        "default" -> "default": _raw_spin_unlock
                                        "default" -> "default"++: perf_event_task_tick
                                          "default" -> "default": perf_adjust_freq_unthr_context
                                          "default" -> "default": __rcu_read_lock
                                          "default" -> "default": __rcu_read_unlock
                                        "default" --> "default"--: ret
                                        "default" -> "default": idle_cpu
                                        "default" -> "default": sched_balance_trigger
                                      "default" --> "default"--: ret
                                      "default" -> "default": run_posix_cpu_timers
                                    "default" --> "default"--: ret
                                    "default" -> "default"++: profile_tick
                                      "default" -> "default"++: profile_pc
                                        "default" -> "default": profile_pc_cb
                                      "default" --> "default"--: ret
                                    "default" --> "default"--: ret
                                    "default" -> "default"++: hrtimer_forward
                                      "default" -> "default": ktime_add_safe
                                      "default" -> "default": ktime_add_safe
                                    "default" --> "default"--: ret
                                  "default" --> "default"--: ret
                                  "default" -> "default": _raw_spin_lock_irq
                                  "default" -> "default": enqueue_hrtimer
                                "default" --> "default"--: ret
                                "default" -> "default"++: hrtimer_update_next_event
                                  "default" -> "default"++: __hrtimer_get_next_event
                                    "default" -> "default": __hrtimer_next_event_base
                                  "default" --> "default"--: ret
                                  "default" -> "default"++: __hrtimer_get_next_event
                                    "default" -> "default": __hrtimer_next_event_base
                                  "default" --> "default"--: ret
                                "default" --> "default"--: ret
                                "default" -> "default": _raw_spin_unlock_irqrestore
                                "default" -> "default"++: tick_program_event
                                  "default" -> "default"++: clockevents_program_event
                                    "default" -> "default"++: ktime_get
                                      "default" -> "default": arch_counter_read
                                    "default" --> "default"--: ret
                                    "default" -> "default": arch_timer_set_next_event_virt
                                  "default" --> "default"--: ret
                                "default" --> "default"--: ret
                              "default" --> "default"--: ret
                            "default" --> "default"--: ret
                            "default" -> "default": gic_eoi_irq
                          "default" --> "default"--: ret
                        "default" --> "default"--: ret
                      "default" --> "default"--: ret
                    "default" --> "default"--: ret
                  "default" --> "fs/namei.o"--: ret
                  "fs/namei.o" -> "default"++: irq_exit_rcu
                    "default" -> "default": irqtime_account_irq
                    "default" -> "default": idle_cpu
                  "default" --> "fs/namei.o"--: ret
                  "fs/namei.o" -> "default"++: preempt_schedule_irq
                    "default" -> "default"++: rcu_note_context_switch
                      "default" -> "default": rcu_qs
                    "default" --> "default"--: ret
                    "default" -> "default"++: raw_spin_rq_lock_nested
                      "default" -> "default": _raw_spin_lock
                    "default" --> "default"--: ret
                    "default" -> "default"++: update_rq_clock
                      "default" -> "default"++: update_irq_load_avg
                        "default" -> "default": decay_load
                        "default" -> "default": decay_load
                        "default" -> "default": decay_load
                      "default" --> "default"--: ret
                    "default" --> "default"--: ret
                    "default" -> "default"++: pick_next_task_fair
                      "default" -> "default"++: pick_task_fair
                        "default" -> "default": update_curr
                        "default" -> "default"++: pick_eevdf
                          "default" -> "default": __pick_first_entity
                          "default" -> "default"++: entity_eligible
                            "default" -> "default": vruntime_eligible
                          "default" --> "default"--: ret
                          "default" -> "default"++: entity_eligible
                            "default" -> "default": vruntime_eligible
                          "default" --> "default"--: ret
                        "default" --> "default"--: ret
                        "default" -> "default"++: dequeue_entities
                          "default" -> "default": update_curr
                          "default" -> "default": clear_buddies.isra.0
                          "default" -> "default"++: __update_load_avg_se
                            "default" -> "default": decay_load
                            "default" -> "default": decay_load
                            "default" -> "default": decay_load
                            "default" -> "default"++: __accumulate_pelt_segments
                              "default" -> "default": decay_load
                              "default" -> "default": decay_load
                            "default" --> "default"--: ret
                          "default" --> "default"--: ret
                          "default" -> "default": __update_load_avg_cfs_rq
                          "default" -> "default"++: update_entity_lag
                            "default" -> "default": avg_vruntime
                          "default" --> "default"--: ret
                          "default" -> "default": __dequeue_entity
                          "default" -> "default": se_is_idle
                          "default" -> "default": update_cfs_group
                          "default" -> "default"++: update_min_vruntime
                            "default" -> "default": __pick_root_entity
                          "default" --> "default"--: ret
                          "default" -> "default": clear_delayed
                          "default" -> "default": __pick_root_entity
                        "default" --> "default"--: ret
                        "default" -> "default": update_curr
                        "default" -> "default"++: pick_eevdf
                          "default" -> "default": __pick_first_entity
                          "default" -> "default"++: entity_eligible
                            "default" -> "default": vruntime_eligible
                          "default" --> "default"--: ret
                          "default" -> "default"++: entity_eligible
                            "default" -> "default": vruntime_eligible
                          "default" --> "default"--: ret
                        "default" --> "default"--: ret
                      "default" --> "default"--: ret
                      "default" -> "default"++: put_prev_entity
                        "default" -> "default": update_curr
                        "default" -> "default": __enqueue_entity
                        "default" -> "default": __update_load_avg_se
                        "default" -> "default": __update_load_avg_cfs_rq
                      "default" --> "default"--: ret
                      "default" -> "default"++: put_prev_entity
                        "default" -> "default": update_curr
                        "default" -> "default": __enqueue_entity
                        "default" -> "default": __update_load_avg_se
                        "default" -> "default": __update_load_avg_cfs_rq
                      "default" --> "default"--: ret
                      "default" -> "default"++: set_next_entity
                        "default" -> "default": clear_buddies.isra.0
                        "default" -> "default": __dequeue_entity
                        "default" -> "default"++: __update_load_avg_se
                          "default" -> "default": decay_load
                          "default" -> "default": decay_load
                          "default" -> "default": decay_load
                          "default" -> "default"++: __accumulate_pelt_segments
                            "default" -> "default": decay_load
                            "default" -> "default": decay_load
                          "default" --> "default"--: ret
                        "default" --> "default"--: ret
                        "default" -> "default": __update_load_avg_cfs_rq
                      "default" --> "default"--: ret
                    "default" --> "default"--: ret
                    "default" -> "default": __traceiter_sched_switch
                    "default" -> "default"++: fpsimd_thread_switch
                      "default" -> "default": fpsimd_save_user_state
                    "default" --> "default"--: ret
                    "default" -> "default": tls_preserve_current_state
                    "default" -> "default": hw_breakpoint_thread_switch
                    "default" -> "default": mte_thread_switch
                    "default" -> "default"++: finish_task_switch.isra.0
                      "default" -> "default": __balance_callbacks
                      "default" -> "default": _raw_spin_unlock
                    "default" --> "default"--: ret
                  "default" --> "fs/namei.o"--: ret
                  "fs/namei.o" -> "fs/dcache.o"++: dput
                    "fs/dcache.o" -> "default": __rcu_read_lock
                    "fs/dcache.o" -> "default": __rcu_read_unlock
                  "fs/dcache.o" --> "fs/namei.o"--: ret
                "fs/namei.o" --> "fs/namei.o"--: ret
                "fs/namei.o" -> "fs/dcache.o"++: dput
                  "fs/dcache.o" -> "default": __rcu_read_lock
                  "fs/dcache.o" -> "default": __rcu_read_unlock
                "fs/dcache.o" --> "fs/namei.o"--: ret
                "fs/namei.o" -> "fs/namespace.o"++: mntput
                  "fs/namespace.o" -> "fs/namespace.o"++: mntput_no_expire
                    "fs/namespace.o" -> "default": __rcu_read_lock
                    "fs/namespace.o" -> "default": __rcu_read_unlock
                  "fs/namespace.o" --> "fs/namespace.o"--: ret
                "fs/namespace.o" --> "fs/namei.o"--: ret
              "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: inode_permission
              "fs/namei.o" -> "fs/namei.o": sb_permission
              "fs/namei.o" -> "fs/namei.o"++: generic_permission
                "fs/namei.o" -> "fs/namei.o"++: acl_permission_check
                  "fs/namei.o" -> "fs/mnt_idmapping.o": make_vfsuid
                "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "default": security_inode_permission
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: walk_component
              "fs/namei.o" -> "fs/namei.o"++: lookup_fast
                "fs/namei.o" -> "fs/dcache.o"++: __d_lookup
                  "fs/dcache.o" -> "default": __rcu_read_lock
                  "fs/dcache.o" -> "default": _raw_spin_lock
                  "fs/dcache.o" -> "fs/dcache.o": d_same_name
                  "fs/dcache.o" -> "default": _raw_spin_unlock
                  "fs/dcache.o" -> "default": __rcu_read_unlock
                "fs/dcache.o" --> "fs/namei.o"--: ret
              "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "fs/namei.o"++: step_into
                "fs/namei.o" -> "fs/namei.o"++: __traverse_mounts
                  "fs/namei.o" -> "fs/namespace.o"++: lookup_mnt
                    "fs/namespace.o" -> "default": __rcu_read_lock
                    "fs/namespace.o" -> "fs/namespace.o": __lookup_mnt
                    "fs/namespace.o" -> "fs/namespace.o": __legitimize_mnt
                    "fs/namespace.o" -> "default": __rcu_read_unlock
                  "fs/namespace.o" --> "fs/namei.o"--: ret
                  "fs/namei.o" -> "fs/dcache.o"++: dput
                    "fs/dcache.o" -> "default": __rcu_read_lock
                    "fs/dcache.o" -> "default": __rcu_read_unlock
                  "fs/dcache.o" --> "fs/namei.o"--: ret
                "fs/namei.o" --> "fs/namei.o"--: ret
                "fs/namei.o" -> "fs/dcache.o"++: dput
                  "fs/dcache.o" -> "default": __rcu_read_lock
                  "fs/dcache.o" -> "default": __rcu_read_unlock
                "fs/dcache.o" --> "fs/namei.o"--: ret
                "fs/namei.o" -> "fs/namespace.o"++: mntput
                  "fs/namespace.o" -> "fs/namespace.o"++: mntput_no_expire
                    "fs/namespace.o" -> "default": __rcu_read_lock
                    "fs/namespace.o" -> "default": __rcu_read_unlock
                  "fs/namespace.o" --> "fs/namespace.o"--: ret
                "fs/namespace.o" --> "fs/namei.o"--: ret
              "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: inode_permission
              "fs/namei.o" -> "fs/namei.o": sb_permission
              "fs/namei.o" -> "fs/namei.o"++: generic_permission
                "fs/namei.o" -> "fs/namei.o": acl_permission_check
              "fs/namei.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "default": security_inode_permission
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/mnt_idmapping.o": make_vfsuid
          "fs/namei.o" --> "fs/namei.o"--: ret
          "fs/namei.o" -> "fs/namei.o"++: open_last_lookups
            "fs/namei.o" -> "fs/namei.o"++: lookup_fast_for_open
              "fs/namei.o" -> "fs/namei.o"++: lookup_fast
                "fs/namei.o" -> "fs/dcache.o"++: __d_lookup
                  "fs/dcache.o" -> "default": __rcu_read_lock
                  "fs/dcache.o" -> "default": _raw_spin_lock
                  "fs/dcache.o" -> "fs/dcache.o": d_same_name
                  "fs/dcache.o" -> "default": _raw_spin_unlock
                  "fs/dcache.o" -> "default": __rcu_read_unlock
                "fs/dcache.o" --> "fs/namei.o"--: ret
                "fs/namei.o" -> "fs/tracefs/inode.o": tracefs_d_revalidate
              "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: step_into
              "fs/namei.o" -> "fs/dcache.o"++: dput
                "fs/dcache.o" -> "default": __rcu_read_lock
                "fs/dcache.o" -> "default": __rcu_read_unlock
              "fs/dcache.o" --> "fs/namei.o"--: ret
            "fs/namei.o" --> "fs/namei.o"--: ret
          "fs/namei.o" --> "fs/namei.o"--: ret
          "fs/namei.o" -> "fs/nfs/dir.o"++: do_open
            "fs/nfs/dir.o" -> "fs/namei.o": complete_walk
            "fs/nfs/dir.o" -> "fs/namei.o": may_create_in_sticky
            "fs/nfs/dir.o" -> "fs/namespace.o"++: mnt_want_write
              "fs/namespace.o" -> "fs/namespace.o"++: mnt_get_write_access
                "fs/namespace.o" -> "fs/namespace.o": __mnt_is_readonly
              "fs/namespace.o" --> "fs/namespace.o"--: ret
            "fs/namespace.o" --> "fs/nfs/dir.o"--: ret
            "fs/nfs/dir.o" -> "fs/namei.o"++: may_open
              "fs/namei.o" -> "fs/namei.o"++: inode_permission
                "fs/namei.o" -> "fs/namei.o": sb_permission
                "fs/namei.o" -> "fs/mnt_idmapping.o": make_vfsuid
                "fs/namei.o" -> "fs/mnt_idmapping.o": make_vfsgid
                "fs/namei.o" -> "fs/tracefs/inode.o"++: tracefs_permission
                  "fs/tracefs/inode.o" -> "fs/tracefs/inode.o": set_tracefs_inode_owner
                  "fs/tracefs/inode.o" -> "fs/namei.o"++: generic_permission
                    "fs/namei.o" -> "fs/namei.o"++: acl_permission_check
                      "fs/namei.o" -> "fs/mnt_idmapping.o": make_vfsuid
                    "fs/namei.o" --> "fs/namei.o"--: ret
                  "fs/namei.o" --> "fs/tracefs/inode.o"--: ret
                "fs/tracefs/inode.o" --> "fs/namei.o"--: ret
                "fs/namei.o" -> "default": security_inode_permission
              "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" --> "fs/nfs/dir.o"--: ret
            "fs/nfs/dir.o" -> "fs/open.o"++: vfs_open
              "fs/open.o" -> "fs/open.o"++: do_dentry_open
                "fs/open.o" -> "fs/namei.o"++: path_get
                  "fs/namei.o" -> "fs/namespace.o": mntget
                "fs/namei.o" --> "fs/open.o"--: ret
                "fs/open.o" -> "fs/namespace.o"++: mnt_get_write_access
                  "fs/namespace.o" -> "fs/namespace.o": __mnt_is_readonly
                "fs/namespace.o" --> "fs/open.o"--: ret
                "fs/open.o" -> "default": try_module_get
                "fs/open.o" -> "default": security_file_open
                "fs/open.o" -> "default": security_locked_down
                "fs/open.o" -> "default": mutex_lock
                "fs/open.o" -> "default": mutex_unlock
                "fs/open.o" -> "mm/readahead.o"++: file_ra_state_init
                  "mm/readahead.o" -> "mm/backing-dev.o": inode_to_bdi
                "mm/readahead.o" --> "fs/open.o"--: ret
              "fs/open.o" --> "fs/open.o"--: ret
            "fs/open.o" --> "fs/nfs/dir.o"--: ret
            "fs/nfs/dir.o" -> "default": security_file_post_open
            "fs/nfs/dir.o" -> "fs/namei.o"++: handle_truncate
              "fs/namei.o" -> "default": security_file_truncate
              "fs/namei.o" -> "fs/open.o"++: do_truncate
                "fs/open.o" -> "fs/inode.o"++: dentry_needs_remove_privs
                  "fs/inode.o" -> "fs/attr.o"++: setattr_should_drop_suidgid
                    "fs/attr.o" -> "fs/attr.o": setattr_should_drop_sgid
                  "fs/attr.o" --> "fs/inode.o"--: ret
                  "fs/inode.o" -> "default"++: security_inode_need_killpriv
                    "default" -> "default"++: cap_inode_need_killpriv
                      "default" -> "fs/xattr.o"++: __vfs_getxattr
                        "fs/xattr.o" -> "fs/xattr.o"++: xattr_resolve_name
                          "fs/xattr.o" -> "fs/bad_inode.o": is_bad_inode
                        "fs/xattr.o" --> "fs/xattr.o"--: ret
                      "fs/xattr.o" --> "default"--: ret
                    "default" --> "default"--: ret
                  "default" --> "fs/inode.o"--: ret
                "fs/inode.o" --> "fs/open.o"--: ret
                "fs/open.o" -> "default": down_write
                "fs/open.o" -> "fs/attr.o"++: notify_change
                  "fs/attr.o" -> "fs/attr.o": may_setattr
                  "fs/attr.o" -> "fs/inode.o"++: current_time
                    "fs/inode.o" -> "default": ktime_get_coarse_real_ts64_mg
                    "fs/inode.o" -> "fs/inode.o": timestamp_truncate
                  "fs/inode.o" --> "fs/attr.o"--: ret
                  "fs/attr.o" -> "fs/mnt_idmapping.o": make_vfsuid
                  "fs/attr.o" -> "fs/mnt_idmapping.o": make_vfsgid
                  "fs/attr.o" -> "default": security_inode_setattr
                  "fs/attr.o" -> "fs/tracefs/inode.o"++: tracefs_setattr
                    "fs/tracefs/inode.o" -> "fs/libfs.o"++: simple_setattr
                      "fs/libfs.o" -> "fs/attr.o"++: setattr_prepare
                        "fs/attr.o" -> "fs/attr.o": inode_newsize_ok
                      "fs/attr.o" --> "fs/libfs.o"--: ret
                      "fs/libfs.o" -> "mm/truncate.o"++: truncate_setsize
                        "mm/truncate.o" -> "mm/truncate.o"++: truncate_pagecache
                          "mm/truncate.o" -> "mm/memory.o"++: unmap_mapping_range
                            "mm/memory.o" -> "mm/memory.o"++: unmap_mapping_pages
                              "mm/memory.o" -> "default": down_read
                              "mm/memory.o" -> "default": up_read
                            "mm/memory.o" --> "mm/memory.o"--: ret
                          "mm/memory.o" --> "mm/truncate.o"--: ret
                          "mm/truncate.o" -> "mm/truncate.o"++: truncate_inode_pages
                            "mm/truncate.o" -> "mm/truncate.o": truncate_inode_pages_range
                          "mm/truncate.o" --> "mm/truncate.o"--: ret
                          "mm/truncate.o" -> "mm/memory.o"++: unmap_mapping_range
                            "mm/memory.o" -> "mm/memory.o"++: unmap_mapping_pages
                              "mm/memory.o" -> "default": down_read
                              "mm/memory.o" -> "default": up_read
                            "mm/memory.o" --> "mm/memory.o"--: ret
                          "mm/memory.o" --> "mm/truncate.o"--: ret
                        "mm/truncate.o" --> "mm/truncate.o"--: ret
                      "mm/truncate.o" --> "fs/libfs.o"--: ret
                      "fs/libfs.o" -> "fs/attr.o"++: setattr_copy
                        "fs/attr.o" -> "fs/inode.o"++: inode_set_ctime_to_ts
                          "fs/inode.o" -> "default": set_normalized_timespec64
                        "fs/inode.o" --> "fs/attr.o"--: ret
                      "fs/attr.o" --> "fs/libfs.o"--: ret
                      "fs/libfs.o" -> "fs/fs-writeback.o": __mark_inode_dirty
                    "fs/libfs.o" --> "fs/tracefs/inode.o"--: ret
                  "fs/tracefs/inode.o" --> "fs/attr.o"--: ret
                  "fs/attr.o" -> "default": security_inode_post_setattr
                "fs/attr.o" --> "fs/open.o"--: ret
                "fs/open.o" -> "default": up_write
              "fs/open.o" --> "fs/namei.o"--: ret
            "fs/namei.o" --> "fs/nfs/dir.o"--: ret
            "fs/nfs/dir.o" -> "fs/namespace.o"++: mnt_drop_write
              "fs/namespace.o" -> "fs/namespace.o": mnt_put_write_access
            "fs/namespace.o" --> "fs/nfs/dir.o"--: ret
          "fs/nfs/dir.o" --> "fs/namei.o"--: ret
          "fs/namei.o" -> "fs/namei.o"++: terminate_walk
            "fs/namei.o" -> "fs/namei.o": drop_links
            "fs/namei.o" -> "fs/namei.o"++: path_put
              "fs/namei.o" -> "fs/dcache.o"++: dput
                "fs/dcache.o" -> "default": __rcu_read_lock
                "fs/dcache.o" -> "default": __rcu_read_unlock
              "fs/dcache.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "fs/namespace.o"++: mntput
                "fs/namespace.o" -> "fs/namespace.o"++: mntput_no_expire
                  "fs/namespace.o" -> "default": __rcu_read_lock
                  "fs/namespace.o" -> "default": __rcu_read_unlock
                "fs/namespace.o" --> "fs/namespace.o"--: ret
              "fs/namespace.o" --> "fs/namei.o"--: ret
            "fs/namei.o" --> "fs/namei.o"--: ret
            "fs/namei.o" -> "fs/namei.o"++: path_put
              "fs/namei.o" -> "fs/dcache.o"++: dput
                "fs/dcache.o" -> "default": __rcu_read_lock
                "fs/dcache.o" -> "default": __rcu_read_unlock
              "fs/dcache.o" --> "fs/namei.o"--: ret
              "fs/namei.o" -> "fs/namespace.o"++: mntput
                "fs/namespace.o" -> "fs/namespace.o"++: mntput_no_expire
                  "fs/namespace.o" -> "default": __rcu_read_lock
                  "fs/namespace.o" -> "default": __rcu_read_unlock
                "fs/namespace.o" --> "fs/namespace.o"--: ret
              "fs/namespace.o" --> "fs/namei.o"--: ret
            "fs/namei.o" --> "fs/namei.o"--: ret
          "fs/namei.o" --> "fs/namei.o"--: ret
        "fs/namei.o" --> "fs/namei.o"--: ret
        "fs/namei.o" -> "fs/namei.o": restore_nameidata
      "fs/namei.o" --> "fs/open.o"--: ret
      "fs/open.o" -> "fs/file.o": fd_install
      "fs/open.o" -> "fs/namei.o"++: putname
        "fs/namei.o" -> "mm/slub.o": kmem_cache_free
      "fs/namei.o" --> "fs/open.o"--: ret
    "fs/open.o" --> "fs/open.o"--: ret
  "fs/open.o" --> "default"--: ret
@enduml
