@startuml
  "default" -> "fs/splice.o"++: do_splice_read
    "fs/splice.o" -> "fs/splice.o"++: copy_splice_read
      "fs/splice.o" -> "mm/slub.o"++: __kmalloc_noprof
        "mm/slub.o" -> "mm/slub.o": prefetch_freepointer.isra.0
      "mm/slub.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "mm/page_alloc.o"++: alloc_pages_bulk_noprof
        "mm/page_alloc.o" -> "default": _raw_spin_trylock
        "mm/page_alloc.o" -> "default": _raw_spin_unlock
      "mm/page_alloc.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "fs/proc/inode.o"++: proc_reg_read_iter
        "fs/proc/inode.o" -> "fs/seq_file.o"++: seq_read_iter
          "fs/seq_file.o" -> "default": mutex_lock
          "fs/seq_file.o" -> "fs/seq_file.o"++: seq_buf_alloc
            "fs/seq_file.o" -> "mm/util.o"++: __kvmalloc_node_noprof
              "mm/util.o" -> "mm/slub.o"++: __kmalloc_node_noprof
                "mm/slub.o" -> "mm/slub.o": prefetch_freepointer.isra.0
              "mm/slub.o" --> "mm/util.o"--: ret
            "mm/util.o" --> "fs/seq_file.o"--: ret
          "fs/seq_file.o" --> "fs/seq_file.o"--: ret
          "fs/seq_file.o" -> "fs/seq_file.o": single_start
          "fs/seq_file.o" -> "fs/proc/meminfo.o"++: meminfo_proc_show
            "fs/proc/meminfo.o" -> "mm/show_mem.o"++: si_meminfo
              "mm/show_mem.o" -> "default"++: nr_blockdev_pages
                "default" -> "default": _raw_spin_lock
                "default" -> "default": _raw_spin_unlock
              "default" --> "mm/show_mem.o"--: ret
            "mm/show_mem.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "mm/swapfile.o"++: si_swapinfo
              "mm/swapfile.o" -> "default": _raw_spin_lock
              "mm/swapfile.o" -> "default": _raw_spin_unlock
            "mm/swapfile.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "mm/util.o"++: vm_memory_committed
              "mm/util.o" -> "default": _raw_spin_lock_irqsave
              "mm/util.o" -> "default": _raw_spin_unlock_irqrestore
            "mm/util.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "mm/show_mem.o"++: si_mem_available
              "mm/show_mem.o" -> "mm/mmzone.o": first_online_pgdat
              "mm/show_mem.o" -> "mm/mmzone.o": next_zone
              "mm/show_mem.o" -> "mm/mmzone.o": next_zone
              "mm/show_mem.o" -> "mm/mmzone.o": next_zone
              "mm/show_mem.o" -> "mm/mmzone.o"++: next_zone
                "mm/mmzone.o" -> "mm/mmzone.o": next_online_pgdat
              "mm/mmzone.o" --> "mm/show_mem.o"--: ret
            "mm/show_mem.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_printf
              "fs/seq_file.o" -> "fs/seq_file.o": seq_vprintf
            "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "mm/util.o"++: vm_commit_limit
              "mm/util.o" -> "mm/hugetlb.o": hugetlb_total_pages
            "mm/util.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_printf
              "fs/seq_file.o" -> "fs/seq_file.o": seq_vprintf
            "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "mm/vmalloc.o": vmalloc_nr_pages
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "mm/percpu.o": pcpu_nr_pages
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "mm/memtest.o": memtest_report_meminfo
            "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_printf
              "fs/seq_file.o" -> "fs/seq_file.o": seq_vprintf
            "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "fs/proc/meminfo.o"++: show_val_kb
              "fs/proc/meminfo.o" -> "fs/seq_file.o"++: seq_put_decimal_ull_width
                "fs/seq_file.o" -> "fs/seq_file.o"++: __seq_puts
                  "fs/seq_file.o" -> "fs/seq_file.o": seq_write
                "fs/seq_file.o" --> "fs/seq_file.o"--: ret
              "fs/seq_file.o" --> "fs/proc/meminfo.o"--: ret
              "fs/proc/meminfo.o" -> "fs/seq_file.o": seq_write
            "fs/proc/meminfo.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "mm/hugetlb.o"++: hugetlb_report_meminfo
              "mm/hugetlb.o" -> "fs/seq_file.o"++: seq_printf
                "fs/seq_file.o" -> "fs/seq_file.o": seq_vprintf
              "fs/seq_file.o" --> "mm/hugetlb.o"--: ret
              "mm/hugetlb.o" -> "fs/seq_file.o"++: seq_printf
                "fs/seq_file.o" -> "fs/seq_file.o": seq_vprintf
              "fs/seq_file.o" --> "mm/hugetlb.o"--: ret
            "mm/hugetlb.o" --> "fs/proc/meminfo.o"--: ret
            "fs/proc/meminfo.o" -> "default": arch_report_meminfo
          "fs/proc/meminfo.o" --> "fs/seq_file.o"--: ret
          "fs/seq_file.o" -> "fs/seq_file.o": single_next
          "fs/seq_file.o" -> "fs/seq_file.o": single_stop
          "fs/seq_file.o" -> "default": mutex_unlock
        "fs/seq_file.o" --> "fs/proc/inode.o"--: ret
      "fs/proc/inode.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "mm/swap.o"++: release_pages
        "mm/swap.o" -> "mm/swap.o"++: folios_put_refs
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/memcontrol.o"++: __mem_cgroup_uncharge_folios
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
          "mm/memcontrol.o" --> "mm/swap.o"--: ret
          "mm/swap.o" -> "mm/page_alloc.o"++: free_unref_folios
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "default": _raw_spin_trylock
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "default": _raw_spin_unlock
          "mm/page_alloc.o" --> "mm/swap.o"--: ret
        "mm/swap.o" --> "mm/swap.o"--: ret
      "mm/swap.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "mm/slub.o": kfree
    "fs/splice.o" --> "fs/splice.o"--: ret
  "fs/splice.o" --> "default"--: ret
  "default" -> "fs/splice.o"++: do_splice_read
    "fs/splice.o" -> "fs/splice.o"++: copy_splice_read
      "fs/splice.o" -> "mm/slub.o"++: __kmalloc_noprof
        "mm/slub.o" -> "mm/slub.o": prefetch_freepointer.isra.0
      "mm/slub.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "mm/page_alloc.o"++: alloc_pages_bulk_noprof
        "mm/page_alloc.o" -> "default": _raw_spin_trylock
        "mm/page_alloc.o" -> "default": _raw_spin_unlock
      "mm/page_alloc.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "fs/proc/inode.o"++: proc_reg_read_iter
        "fs/proc/inode.o" -> "fs/seq_file.o"++: seq_read_iter
          "fs/seq_file.o" -> "default": mutex_lock
          "fs/seq_file.o" -> "fs/seq_file.o": single_start
          "fs/seq_file.o" -> "fs/seq_file.o": single_stop
          "fs/seq_file.o" -> "default": mutex_unlock
        "fs/seq_file.o" --> "fs/proc/inode.o"--: ret
      "fs/proc/inode.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "mm/swap.o"++: release_pages
        "mm/swap.o" -> "mm/swap.o"++: folios_put_refs
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/memcontrol.o"++: __mem_cgroup_uncharge_folios
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
          "mm/memcontrol.o" --> "mm/swap.o"--: ret
          "mm/swap.o" -> "mm/page_alloc.o"++: free_unref_folios
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "default": _raw_spin_trylock
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "default": _raw_spin_unlock
          "mm/page_alloc.o" --> "mm/swap.o"--: ret
        "mm/swap.o" --> "mm/swap.o"--: ret
      "mm/swap.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "mm/slub.o": kfree
    "fs/splice.o" --> "fs/splice.o"--: ret
  "fs/splice.o" --> "default"--: ret
  "default" -> "fs/splice.o"++: do_splice_read
    "fs/splice.o" -> "fs/splice.o"++: copy_splice_read
      "fs/splice.o" -> "mm/slub.o"++: __kmalloc_noprof
        "mm/slub.o" -> "mm/slub.o": prefetch_freepointer.isra.0
      "mm/slub.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "mm/page_alloc.o"++: alloc_pages_bulk_noprof
        "mm/page_alloc.o" -> "default": _raw_spin_trylock
        "mm/page_alloc.o" -> "default": _raw_spin_unlock
      "mm/page_alloc.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "fs/proc/inode.o"++: proc_reg_read_iter
        "fs/proc/inode.o" -> "fs/seq_file.o"++: seq_read_iter
          "fs/seq_file.o" -> "default": mutex_lock
          "fs/seq_file.o" -> "fs/seq_file.o": single_start
          "fs/seq_file.o" -> "fs/seq_file.o": single_stop
          "fs/seq_file.o" -> "default": mutex_unlock
        "fs/seq_file.o" --> "fs/proc/inode.o"--: ret
      "fs/proc/inode.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "mm/swap.o"++: release_pages
        "mm/swap.o" -> "mm/swap.o"++: folios_put_refs
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/swap.o": __page_cache_release
          "mm/swap.o" -> "mm/memcontrol.o"++: __mem_cgroup_uncharge_folios
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
            "mm/memcontrol.o" -> "mm/memcontrol.o": uncharge_folio
          "mm/memcontrol.o" --> "mm/swap.o"--: ret
          "mm/swap.o" -> "mm/page_alloc.o"++: free_unref_folios
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "default": _raw_spin_trylock
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "mm/page_alloc.o": get_pfnblock_flags_mask
            "mm/page_alloc.o" -> "mm/page_alloc.o": free_unref_page_commit
            "mm/page_alloc.o" -> "default": _raw_spin_unlock
          "mm/page_alloc.o" --> "mm/swap.o"--: ret
        "mm/swap.o" --> "mm/swap.o"--: ret
      "mm/swap.o" --> "fs/splice.o"--: ret
      "fs/splice.o" -> "mm/slub.o": kfree
    "fs/splice.o" --> "fs/splice.o"--: ret
  "fs/splice.o" --> "default"--: ret
@enduml
