# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the kernfs pseudo filesystem
#

CFLAGS_file.o := -O0
CFLAGS_dir.o := -O0
CFLAGS_inode.o := -O0
CFLAGS_mount.o := -O0
CFLAGS_symlink.o := -O0

obj-y		:= mount.o inode.o dir.o file.o symlink.o
