# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the sysfs virtual filesystem
#

CFLAGS_file.o := -O0
CFLAGS_dir.o := -O0
CFLAGS_group.o := -O0
CFLAGS_mount.o := -O0
CFLAGS_symlink.o := -O0

obj-y		:= file.o dir.o symlink.o mount.o group.o
